export {FasterIcon} from "./FasterIcon"
export {DiscordIcon} from "./DiscordIcon"
export {DefiIcon} from "./DefiIcon"
export {CaretLeft} from "./CaretLeft"
export {TelegramIcon} from "./TelegramIcon"
export {SaferIcon} from "./SaferIcon"
export {CaretRight} from "./CaretRight"
export {Xicon} from "./Xicon"